[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_BACKEND_URL = "https://unisoruyor32-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200